# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CodePc.pl
email: codepc@interia.pl
description: >- # this means to ignore newlines until "baseurl:"
  Strona dotyczy programowania.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://plcodepc.github.io/blog_site
twitter_username: jekyllrb
github_username:  plcodepc
meta_description: "Jekyll template, Medium styled, free for bloggers."
google_analytics: 'UA-46278016-1'
disqus: ''
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
email: codepc@interia.pl


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
     layouts: "post"
     title: "mytitle"
      #values




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
